# Linting configuration for dockerfiles

# For more information visit https://github.com/hadolint/hadolint?tab=readme-ov-file#configure
failure-threshold: warning # string name of threshold level (error | warning | info | style | ignore | none)
format: tty # string Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
ignored: [] # [string] list of rules
# label-schema: # See Linting Labels below for specific label-schema details
#   author: # string Your name
#   contact: # string email address
#   created: # timestamp rfc3339 datetime
#   version: # string semver
#   documentation: # string url
#   git-revision: # string hash
#   license: # string spdx
no-color: false # boolean true | false
no-fail: false # boolean true | false
override:
  error: [] # [string] list of rules
  warning: [DL3015] # [string] list of rules
  info: [DL3008] # [string] list of rules
  style: [] # [string] list of rules
# strict-labels: # boolean true | false
# disable-ignore-pragma: # boolean true | false
# trustedRegistries: # string | [string] registry or list of registries
