ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]

COPY . /tmp/eolo/
RUN ls /tmp/eolo/

RUN mkdir /tmp/eolo/build
WORKDIR /tmp/eolo/build
RUN  . "$HOME/.cargo/env" && cmake ../ --preset deps-docker
RUN ninja all && \
    ninja install

# Remove all eolo install
RUN cd / && rm -rf /tmp/eolo && rm -rf /install/include/eolo && rm -rf /install/lib/libeolo* && rm -rf /install/lib/cmake/eolo* && rm -rf /install/share/eolo*

WORKDIR /
