//=================================================================================================
// Copyright (C) 2023-2024 EOLO Contributors
// MIT License
//=================================================================================================

#pragma once

#include <cstdint>
#include <string_view>

namespace eolo::utils
{

// These are autogenerated by the build system from version.in

static constexpr std::uint8_t VERSION_MAJOR = 0;
static constexpr std::uint8_t VERSION_MINOR = 0;
static constexpr std::uint16_t VERSION_PATCH = 0;

static constexpr std::string_view REPO_BRANCH = "bag_recorder";
static constexpr std::string_view BUILD_PROFILE = "Debug";
static constexpr std::string_view REPO_HASH = "9f6c9b2";

} // namespace eolo::utils
