name: "Build Documentation"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: false
          # Share repository cache between workflows.
          repository-cache: true
      - name: Build Docs
        env:
          BUILDBUDDY_KEY: ${{ secrets.BUILDBUDDY_KEY }}
        run: bazelisk build docs --config remote-cache --remote_header="$BUILDBUDDY_KEY"
      - name: upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/bazel-out/k8-fastbuild/bin/docs/_build/html
  deploy-docs:
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token:
        write
        # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ needs.build-docs.outputs.page_url }}
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
