name: Linting
on:
  pull_request:
  push:
    branches: main
jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout self
      uses: actions/checkout@v2
    - name: Run ShellCheck
      run: .github/scripts/shellcheck.sh
  lint-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout self
      uses: actions/checkout@v2
    - name: Run ShellCheck
      run: .github/scripts/hadolint.sh
    - name: Spell Check Repo
      run: .github/scripts/spellcheck.sh
